# Generated by Django 5.0.1 on 2024-02-07 00:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Account', '0003_customuser_is_staff_customuser_superuser_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='superuser',
        ),
    ]
